---
version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0
  apps: expel-io/apps@1.5.0

workflows:
  quality-check:
    jobs:
      - checkout-code:
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - pre-commit:
          requires:
            - checkout-code
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - validate:
          requires:
            - checkout-code
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - apps/scan-tf:
          context: infra-2.0
          requires:
            - pre-commit
            - validate
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/

jobs:
  checkout-code:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - "./*"
  pre-commit:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - attach_workspace:
          at: .
      - run:
          name: install & run pre-commit tests
          command: |
            cd /tmp
            curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-Linux-amd64.tar.gz
            tar -xzf terraform-docs.tar.gz
            chmod +x terraform-docs
            sudo mv terraform-docs /bin/terraform-docs
            rm terraform-docs.tar.gz
            cd /home/circleci/project
            pip install pre-commit
            pre-commit install
            pre-commit run --all-files
  validate:
    executor:
      name: terraform/default
      tag: "1.1.3"
    steps:
      - attach_workspace:
          at: .
      - terraform/fmt
      - terraform/validate
