---
version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

workflows:
  validate-and-security-scan:
    jobs:
      - checkout-code:
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - validate:
          requires:
            - checkout-code
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - security-scan:
          requires:
            - validate
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/

jobs:
  checkout-code:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - "./*"
  validate:
    executor:
      name: terraform/default
      tag: "1.1.3"
    steps:
      - attach_workspace:
          at: .
      - terraform/fmt
      - terraform/validate
  security-scan:
    docker:
      - image: aquasec/tfsec-ci:v1.0
        user: root
    steps:
      - attach_workspace:
          at: .
      - run:
          name: perform security scan
          command: tfsec .
