---
version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

workflows:
  quality-check:
    jobs:
      - checkout-code:
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - pre-commit:
          requires:
            - checkout-code
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - validate:
          requires:
            - checkout-code
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/
      - security-scan:
          requires:
            - validate
          filters:
            branches:
              only:
                - /.*/
            tags:
              ignore:
                - /.*/

jobs:
  checkout-code:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - "./*"
  pre-commit:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - attach_workspace:
          at: .
      - run: |
          pip install gitpython pre-commit
          pre-commit install
          pre-commit run --files $$(git diff --name-only origin)
  validate:
    executor:
      name: terraform/default
      tag: "1.1.3"
    steps:
      - attach_workspace:
          at: .
      - terraform/fmt
      - terraform/validate
  security-scan:
    docker:
      - image: aquasec/tfsec-ci:v1.19
        user: root
    steps:
      - attach_workspace:
          at: .
      - run:
          name: perform security scan
          command: tfsec .
